### ISSUE TITLE
Unable to reach service network (10.96.0.0/12) from windows pods when using vxlan

### ISSUE THREAD

**Issue by WeetA34** [kubernetes-sigs/sig-windows-tools#101] opened 2020-09-07 08:21 UTC
Hi,

i followed the installation procedure from https://v1-17.docs.kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/
I'm able to create pods but they're not able to reach the service network (10.96.0.0/12)
I read that ping doesn't work by design but i'm not able to reach it through Test-NetConnection
I tried different version of docker, windows, kubernetes, flannel & cni plugin.
I'm using 3 VMs (Linux master, linux worker and windows worker) on an Hyper-V workstation.
Spoofing is enabled.
Linux version is CentOS 7

No issue with l2bridge but i can't use it on the target infrastructure.

any ideas?
Thank you

**Comment by WeetA34** [comment] 2020-09-08 07:02
FYI, i have no issue with only 2 nodes (1 linux master and 1 windows worker)

**Comment by WeetA34** [comment] 2020-09-09 09:17
when i curl https://10.96.0.1 from my windows pod (10.244.2.4/8), i see the following trafic on the master node:
```
# tcpdump -nn -i any net 10.244.2.0/24
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
11:01:57.143352 IP 10.244.2.0.65472 > 192.168.168.2.6443: Flags [SEW], seq 325971702, win 64860, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
11:02:00.144316 IP 10.244.2.0.65473 > 192.168.168.2.6443: Flags [SEW], seq 325971702, win 64860, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
11:02:06.156979 IP 10.244.2.0.65472 > 192.168.168.2.6443: Flags [S], seq 325971702, win 64860, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
```

**Comment by WeetA34** [comment] 2020-09-09 09:49
it's supposed to be fixed in 1.18
https://github.com/kubernetes/kubernetes/pull/87792
But i still have the issue with 1.18.8

**Comment by lippertmarkus** [comment] 2020-09-10 06:02
@WeetA34 could you try using Windows Server 2019 with february 2020 updates? I remember newer versions did only work sporadically for me.

**Comment by llyons** [comment] 2020-10-12 20:37
I believe we have this same issue.   a hybrid cluster with kubernetes 1.19.2   We are able to reach the webapps on the linux node with the service ip or clusterip.   But the pods running on the windows node (which shows as ready and pods / containers running) are not reachable.    We have a couple pods running simple web applications on the windows node and can only get to them via the NODE ip : port.

We are using Centos 7 for linux master and worker and Windows server 2019 v1809 on the windows node.

**Comment by jsturtevant** [comment] 2020-10-15 19:45
@WeetA34 can you share the logs of flannel pod?  This could be a duplicate of #103

**Comment by Celthi** [comment] 2020-12-03 03:59
> FYI, i have no issue with only 2 nodes (1 linux master and 1 windows worker)

I have issues with 2 nodes (1 Linux master and 1 windows worker).  I cannot reach the service on the Windows worker from the Linux machine. I even cannot access the Windows service through node port. But the pod on Windows is running fine. I'm following the page in https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/ . Do you happen to know some tips that I can proceed to troubleshoot. Thanks.

**Comment by Celthi** [comment] 2020-12-07 07:53
> @WeetA34 can you share the logs of flannel pod? This could be a duplicate of #103
```
[root@tec-l-014627 containerized-aba-test]# kubectl get pods -n kube-system
NAME                                   READY   STATUS    RESTARTS   AGE
coredns-f9fd979d6-9g86d                1/1     Running   1          4d18h
coredns-f9fd979d6-s75qt                1/1     Running   1          4d18h
etcd-tec-l-014627                      1/1     Running   1          4d17h
kube-apiserver-tec-l-014627            1/1     Running   1          4d17h
kube-controller-manager-tec-l-014627   1/1     Running   1          4d17h
kube-flannel-ds-8v2br                  1/1     Running   2          4d2h
kube-flannel-ds-windows-amd64-jmhp5    1/1     Running   4          3d23h
kube-proxy-d7dfv                       1/1     Running   1          4d2h
kube-proxy-windows-5t85c               1/1     Running   3          4d
kube-scheduler-tec-l-014627            1/1     Running   1          4d17h
```
Hi @jsturtevant Which pod's log do you think will help for troubleshooting? Could you give some tips so I can try them and update the logs here is you are interested?

**Comment by jsturtevant** [comment] 2020-12-07 16:21
@Celthi What is your server version (`cmd /c ver`)?

Could you get the output for:

```
kubectl logs -n kube-system kube-flannel-ds-windows-amd64-jmhp5 
kubectl logs -n kube-system kube-proxy-windows-5t85c 
```

They've been running for 4 days so there will be alot of logs.  Either can restart them and capture the logs or look for any errors...

**Comment by WeetA34** [comment] 2020-12-07 17:02
Hello,
sorry for the delay. As it didn't work as expected, i deleted everything.

But it seems i was not clear about the issue i encountered when i read your comments.
Communication issue was from windows pods to service network used for dns resolution, kubernetes api, ...
As i created the cluster for testing Google Agones with Windows, i was not at the step of accessing windows pod from external.
Agones SDK container inside the windows pod was not able to reach the Kubernetes APi so it failed the pod.

**Comment by Celthi** [comment] 2020-12-08 06:13
> @Celthi What is your server version (`cmd /c ver`)?
> 
> Could you get the output for:
> 
> ```
> kubectl logs -n kube-system kube-flannel-ds-windows-amd64-jmhp5 
> kubectl logs -n kube-system kube-proxy-windows-5t85c 
> ```
> 
> They've been running for 4 days so there will be alot of logs. Either can restart them and capture the logs or look for any errors...

The output of the `cmd /c ver` is Microsoft Windows [Version 10.0.17763.1282]. I realized that I should use `host-gw` instead of `vxlan` according to  https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers

After I use `host-gw` and re-create the cluster, the issue is gone. A rookie mistake. Do you happen to know why we should use `host-gw` for network instead of `vxlan`?

**Closed** 2021-05-07 08:57 UTC
Labels: lifecycle/rotten
