### ISSUE TITLE
The pods can't reach the network

### ISSUE THREAD

**Issue by Tehacz** [kubernetes-sigs/sig-windows-tools#92] opened 2020-05-29 09:16 UTC
Hi,

I have a mixed cluster. The pods on linux machines are working properly but the pods scheduled on windows machine cannot reach outside world. They only can ping themselves and master node IP. They cant reach linux nodes or for example a 8.8.8.8. Dns names are resolved though. 

In the flannel 0.12 there is constant error log: 
Failed to list *v1.Node: Get https://xxxx:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available\n","stream":"stderr"

Any solution to this problem?

**Comment by oe-hbk** [comment] 2020-06-01 16:20
Ping (ICMP) will not work from within a windows pod to connect to service IPs (like the DNS server)  To do actual tests against services, you should to  a curl or  Test-NetConnection -Port XX  type of call.

**Comment by giskou** [comment] 2020-06-16 14:02
A restart of the flannel pod (just delete the pods that give out this error and the daemon set will recreate it) seems to help.
From what I understand, this only happens if flannel has to create the HCN network, which is removed on a reboot.
On the second run, after the pod restart, the HCN network is already there and everything seems to work.

**Comment by xunchangguo** [comment] 2020-08-26 09:53
i have the same error. but still now do not found a solution to this problem

**Comment by jsturtevant** [comment] 2020-10-14 22:50
This is a duplicate of #103. Closing this in favor of that issue  which is currently active and has a few work around listed.

/close

**Closed** 2020-10-14 22:50 UTC
